#10) OBTENHA, USANDO REQUESTS OU URLLIB, DENTRO DE SEU PROGRAMA EM PYTHON, O CSV DO LINK:
#HTTPS://SITES.GOOGLE.COM/SITE/DR2FUNDAMENTOSPYTHON/ARQUIVOS/WINTER_OLYMPICS_MEDALS.CSV
#E:
#DENTRE OS SEGUINTES PAÍSES NÓRDICOS: SUÉCIA, DINAMARCA E NORUEGA,
# VERIFIQUE: NO SÉCULO XXI (A PARTIR DE 2001), QUAL FOI O MAIOR MEDALHISTA
# DE OURO, CONSIDERANDO APENAS AS SEGUINTES MODALIDADES:
#CURLING
#PATINAÇÃO NO GELO (SKATING)
#ESQUI (SKIING)
#HÓQUEI SOBRE O GELO (ICE HOCKEY)
#PARA CADA ESPORTE, CONSIDERE TODAS AS MODALIDADES, TANTO NO MASCULINO QUANTO
# NO FEMININO. SUA RESPOSTA DEVE IMPRIMIR UM RELATÓRIO MOSTRANDO O TOTAL DE
# MEDALHAS DE CADA UM DOS PAÍSES E EM QUE ESPORTE, ANO, CIDADE E GÊNERO
# (MASCULINO OU FEMININO) CADA MEDALHA FOI OBTIDA.