#11) OBTENHA, USANDO REQUESTS OU URLLIB, DENTRO DE SEU PROGRAMA EM PYTHON, O CSV DO LINK:
#HTTPS://SITES.GOOGLE.COM/SITE/DR2FUNDAMENTOSPYTHON/ARQUIVOS/VIDEO_GAMES_SALES_AS_AT_22_DEC_2016.CSV
#OBTENHA, DENTRE OS JOGOS DO GÊNERO DE AÇÃO (ACTION), TIRO (SHOOTER) E PLATAFORMA (PLATFORM):
#QUAIS SÃO AS TRÊS MARCAS QUE MAIS PUBLICARAM JOGOS DOS
# TRÊS GÊNEROS COMBINADOS? INDIQUE TAMBÉM O TOTAL DE JOGOS DE CADA MARCA.
#QUAIS SÃO AS TRÊS MARCAS QUE MAIS VENDERAM OS TRÊS GÊNEROS
# COMBINADOS? INDIQUE TAMBÉM O TOTAL DE VENDAS DE CADA MARCA.
#QUAL É A MARCA COM MAIS PUBLICAÇÕES EM CADA UM DOS GÊNEROS
# NOS ÚLTIMOS DEZ ANOS NO JAPÃO? INDIQUE TAMBÉM O NÚMERO TOTAL DE JOGOS DELA.
#QUAL FOI A MARCA QUE MAIS VENDEU EM CADA UM DESSES GÊNEROS
# NOS ÚLTIMOS DEZ ANOS, NO JAPÃO? INDIQUE TAMBÉM O TOTAL DE VENDAS DELA.
