#12-B) ESCREVA UM PROGRAMA QUE OBTENHA DO USUÁRIO UMA SIGLA
# DO ESTADO DA REGIÃO CENTRO-OESTE E APRESENTA SUAS INFORMAÇÕES CORRESPONDENTES NA TABELA.
# O RESULTADO DEVE APRESENTAR APENAS O CONTEÚDO, SEM FORMATAÇÃO.
# OU SEJA, AS TAGS NÃO DEVEM APARECER. NÃO ESQUEÇA DE CHECAR SE A SIGLA PERTENCE À REGIÃO.
