#11) OBTENHA, USANDO REQUESTS OU URLLIB, DENTRO DE SEU PROGRAMA EM PYTHON, O CSV DO LINK:
#HTTPS://SITES.GOOGLE.COM/SITE/DR2FUNDAMENTOSPYTHON/ARQUIVOS/VIDEO_GAMES_SALES_AS_AT_22_DEC_2016.CSV

#OBTENHA, DENTRE OS JOGOS DO GÊNERO DE AÇÃO (ACTION), TIRO (SHOOTER) E PLATAFORMA (PLATFORM):

# 1 QUAIS SÃO AS TRÊS MARCAS QUE MAIS PUBLICARAM JOGOS DOS
# TRÊS GÊNEROS COMBINADOS? INDIQUE TAMBÉM O TOTAL DE JOGOS DE CADA MARCA.

# 2 QUAIS SÃO AS TRÊS MARCAS QUE MAIS VENDERAM OS TRÊS GÊNEROS
# COMBINADOS? INDIQUE TAMBÉM O TOTAL DE VENDAS DE CADA MARCA.

# 3 QUAL É A MARCA COM MAIS PUBLICAÇÕES EM CADA UM DOS GÊNEROS
# NOS ÚLTIMOS DEZ ANOS NO JAPÃO? INDIQUE TAMBÉM O NÚMERO TOTAL DE JOGOS DELA.

# 4 QUAL FOI A MARCA QUE MAIS VENDEU EM CADA UM DESSES GÊNEROS
# NOS ÚLTIMOS DEZ ANOS, NO JAPÃO? INDIQUE TAMBÉM O TOTAL DE VENDAS DELA.


import requests

link = "https://sites.google.com/site/dr2fundamentospython/arquivos/Video_Games_Sales_as_at_22_Dec_2016.csv"

data = requests.get(link).text
linhas = data.splitlines()

for lin in linhas:
    colunas = lin.split(",")

print(colunas)